# Generated by Django 3.1.5 on 2021-02-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=20)),
                ('No_of_persons', models.IntegerField()),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Food', models.CharField(max_length=30)),
                ('Occasion', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
