# Generated by Django 3.1.5 on 2021-02-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210227_2234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservations',
            new_name='Contact',
        ),
    ]
