# Generated by Django 3.1.5 on 2021-02-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210227_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
