# Generated by Django 3.1.4 on 2020-12-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField()),
                ('Persons', models.IntegerField()),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Food', models.CharField(max_length=100)),
                ('Occasion', models.CharField(max_length=100)),
            ],
        ),
    ]
